version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_NAME=bank_admin_db
      - DB_USER=postgres
      - DB_PASSWORD=admin123
      - JWT_SECRET=fe/N+R/Wv9pXyGhH3QiaDNLykPHHdhwwOppoFH/gZNg=
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./backend/uploads:/app/uploads

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

  store-frontend:
    build:
      context: ./store-frontend
      dockerfile: Dockerfile
    ports:
      - "4000:80"
    depends_on:
      - backend
